export const claims = [
  "Mladým: víte, že dokážete rozhodnout volby?",
  "Hnutí ano prostě chce žít v minulosti bez perspektivy.",
  "Boj s korupcí, ne udávání lidí.",
  "Investice do sportu a kultury jsou zárukou zdravé společnosti.",
  "Potřebujeme obnovit rovnováhu přírody!",
  "Byty je třeba stavět, ne danit.",
  "Nejvyšší čas zastavit zadlužování naší země!",
  "udělejme z česka sebevědomého spojence",
  "Místo byrokratického pekla skutečná digitalizace",
  "Staňme se digitálním tygrem!",
  "Veřejné finance průhledně a čistě",
  "Dítě potřebuje náruč jedné pečující osoby!",
  "Politik má sloužit lidem a nutit stát, aby fungoval stejně",
  "Podpořte finančně piráty a starosty",
  "pojďme postavit ekonomiku na nohy",
  "2 % z rozpočtu pro armádu vybojujeme!",
  "kultura si zaslouží 1 % z rozpočtu",
  "na šikaně živnostníků se podílet nebudeme",
  "skutečně digitální stát, na co máme internet?",
  "pojďme zreformovat školství. od základů.",
  "finance řízené podle plánu",
  "vraťme lesům jejich zdraví",
  "1000 korun pro každého seniora z dotací Agrofertu. Ať si pan Babiš platí předvolební dárečky ze svého.",
  "Máme už dost nekonečných korupčních kauz. Po volbách s nimi zatočíme.",
  "Místo jednolitých polí pestrá krajina.",
  "je čas vyrazit pomoci na jižní moravu!",
];

export const generators = [
  { url: "https://source.unsplash.com/800x800/?monkey", weight: 6 },
  { url: "https://source.unsplash.com/800x800/?pirate", weight: 3 },
  { url: "https://source.unsplash.com/800x800/?anarchy", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?rum", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?pony", weight: 3 },
  { url: "https://source.unsplash.com/800x800/?gold", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?unicorn", weight: 4 },
  { url: "https://source.unsplash.com/800x800/?parrot", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?riot", weight: 5 },
  { url: "https://source.unsplash.com/800x800/?revolt", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?lgbt", weight: 4 },
  { url: "https://source.unsplash.com/800x800/?gorilla", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?meerkat", weight: 3 },
  { url: "https://source.unsplash.com/800x800/?hedgehog", weight: 2 },
];

export default claims;
